name: Build, Test and Package Snapshots

on:
  push:
    paths:
    - 'src/**'
    - 'test/**'
    - '.github/workflows/main.yml'

jobs:
  build_for_windows:
    runs-on: windows-latest
    name: Build for Windows
    steps:
    - uses: actions/checkout@v3
    - name: Make
      run: make test # build + test
      env:
        CC: gcc
    - run: |
        mkdir -p artifacts/windows
        cp bin/dasm.exe artifacts/windows/dasm.exe
    - uses: actions/upload-artifact@v3
      with :
        name: dasm snapshot builds
        path: artifacts

  build_for_mac:
    runs-on: macos-latest
    name: Build for Mac
    steps:
    - uses: actions/checkout@v3
    - name: Make
      run: make test # build + test
      env:
        CC: gcc
    - run: |
        mkdir -p artifacts/macos
        cp bin/dasm artifacts/macos/dasm
    - uses: actions/upload-artifact@v3
      with :
        name: dasm snapshot builds
        path: artifacts

  build_for_linux:
    runs-on: ubuntu-latest
    name: Build for Linux
    steps:
    - uses: actions/checkout@v3
    - name: Make
      run: make test # build + test
      env:
        CC: gcc
    - run: |
        mkdir -p artifacts/linux
        cp bin/dasm artifacts/linux/dasm
    - uses: actions/upload-artifact@v3
      with :
        name: dasm snapshot builds
        path: artifacts
        
